<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.5 on win32)" generated="20210330 11:55:12.284" rpa="false">
<suite id="s1" name="Buttons" source="C:\Users\CJ\Codes\Python\Automação Mobile\tests\buttons.robot">
<test id="s1-t1" name="Deve realizar um clique simples">
<kw name="Open Session" library="base" type="setup">
<kw name="Set Appium Timeout" library="AppiumLibrary">
<doc>Sets the timeout in seconds used by various keywords.</doc>
<arguments>
<arg>5</arg>
</arguments>
<status status="PASS" starttime="20210330 11:55:12.644" endtime="20210330 11:55:12.644"></status>
</kw>
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Emulator</arg>
<arg>app=${EXECDIR}/app/twp.apk</arg>
</arguments>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210330 11:55:14.799" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210330 11:55:14.781" endtime="20210330 11:55:14.799"></status>
</kw>
<msg timestamp="20210330 11:55:14.800" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:14.820" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\CJ\Codes\Python\Automação Mobile\tests/app/twp.apk' does not exist or is not accessible
</msg>
<status status="FAIL" starttime="20210330 11:55:12.644" endtime="20210330 11:55:14.820"></status>
</kw>
<status status="FAIL" starttime="20210330 11:55:12.643" endtime="20210330 11:55:14.820"></status>
</kw>
<kw name="Close Session" library="base" type="teardown">
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210330 11:55:14.822" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210330 11:55:14.821" endtime="20210330 11:55:14.822"></status>
</kw>
<msg timestamp="20210330 11:55:14.823" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:14.823" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210330 11:55:14.821" endtime="20210330 11:55:14.823"></status>
</kw>
<status status="FAIL" starttime="20210330 11:55:14.820" endtime="20210330 11:55:14.824">No application is open</status>
</kw>
<tags>
<tag>short</tag>
</tags>
<status status="FAIL" starttime="20210330 11:55:12.642" endtime="20210330 11:55:14.824" critical="yes">Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\CJ\Codes\Python\Automação Mobile\tests/app/twp.apk' does not exist or is not accessible


Also teardown failed:
No application is open</status>
</test>
<test id="s1-t2" name="Deve realizar um clique longo">
<kw name="Open Session" library="base" type="setup">
<kw name="Set Appium Timeout" library="AppiumLibrary">
<doc>Sets the timeout in seconds used by various keywords.</doc>
<arguments>
<arg>5</arg>
</arguments>
<status status="PASS" starttime="20210330 11:55:14.825" endtime="20210330 11:55:14.825"></status>
</kw>
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Emulator</arg>
<arg>app=${EXECDIR}/app/twp.apk</arg>
</arguments>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210330 11:55:16.921" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210330 11:55:16.918" endtime="20210330 11:55:16.921"></status>
</kw>
<msg timestamp="20210330 11:55:16.923" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:16.926" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\CJ\Codes\Python\Automação Mobile\tests/app/twp.apk' does not exist or is not accessible
</msg>
<status status="FAIL" starttime="20210330 11:55:14.826" endtime="20210330 11:55:16.926"></status>
</kw>
<status status="FAIL" starttime="20210330 11:55:14.825" endtime="20210330 11:55:16.926"></status>
</kw>
<kw name="Close Session" library="base" type="teardown">
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210330 11:55:16.931" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210330 11:55:16.928" endtime="20210330 11:55:16.931"></status>
</kw>
<msg timestamp="20210330 11:55:16.932" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:16.935" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210330 11:55:16.928" endtime="20210330 11:55:16.935"></status>
</kw>
<status status="FAIL" starttime="20210330 11:55:16.927" endtime="20210330 11:55:16.936">No application is open</status>
</kw>
<tags>
<tag>long</tag>
</tags>
<status status="FAIL" starttime="20210330 11:55:14.825" endtime="20210330 11:55:16.936" critical="yes">Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\Users\CJ\Codes\Python\Automação Mobile\tests/app/twp.apk' does not exist or is not accessible


Also teardown failed:
No application is open</status>
</test>
<status status="FAIL" starttime="20210330 11:55:12.285" endtime="20210330 11:55:16.940"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2">Critical Tests</stat>
<stat pass="0" fail="2">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">long</stat>
<stat pass="0" fail="1">short</stat>
</tag>
<suite>
<stat pass="0" fail="2" id="s1" name="Buttons">Buttons</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210330 11:55:14.800" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:14.823" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:16.923" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210330 11:55:16.932" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
